#!/bin/bash

echo -e "\033c"

NONE='\033[0m'
RED='\033[0;31m'
LRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
LBLUE='\033[1;34m'
BLUE='\033[0;34m'

echo -e ${LRED}"Updater for depmaker"${NONE}
echo ""
echo ""
echo -e ${YELLOW}"Backup and erase old version"${NONE}
echo ""
mv ./depmaker ./depmaker-old
if [ $? -eq 0 ]
then
echo -e ${LBLUE}"DONE"${NONE}
else
echo -e ${RED}"Unable to backup, does depmaker exist?"${NONE}
echo ""
exit 1
fi
echo ""
echo ""
echo ""
echo -e ${GREEN}"Downloading latest version"${NONE}
wget https://github.com/MZO9400/depmaker/raw/master/depmaker &> /dev/null
if [ -f ./depmaker ]
	then
		sleep 1
		echo -e "\033c"
   		echo -e ${GREEN}"Latest depmaker has been downloaded."${NONE}
		chmod +x depmaker
		echo ""
		exit 0
	else
		sleep 2
		echo ""
   		echo -e ${RED}"DEPMAKER failed to download."${NONE}
		echo ""
		exit 1
fi
